// Generated by jextract

package dgroomes.bindings;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$0 {

    static final FunctionDescriptor luckyNumber$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle luckyNumber$MH = RuntimeHelper.downcallHandleVariadic(
        "luckyNumber",
        constants$0.luckyNumber$FUNC
    );
}


